name: Review Change Request

on:
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack on Lint Start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 Starting linting for PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Notify Slack on Lint Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ Linting passed for PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Notify Slack on Lint Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ Linting failed in PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Notify Slack on Test Start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 Starting tests for PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run ESLint
        run: npm run lint

      - name: Notify Slack on Test Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ Tests passed for PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Notify Slack on Test Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ Tests failed in PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Notify Slack on Overall Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ All checks passed for PR #${{ github.event.pull_request.number }}\nRepository: ${{ github.repository }}\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}
