name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Notify Slack on Build Start
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🏗️ Starting new package build from main branch\nRepository: ${{ github.repository }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Get package info
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          VERSION=$(node -p "require('./package.json').version")
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "version=${VERSION}-SNAPSHOT.${COMMIT_HASH}" >> $GITHUB_OUTPUT

      - name: Build container
        run: podman build -t ${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }} .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag container
        run: |
          podman tag ${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }} ghcr.io/stefan79/${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }}
          podman tag ${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }} ghcr.io/stefan79/${{ steps.package.outputs.name }}:latest

      - name: Push container
        run: |
          podman push ghcr.io/stefan79/${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }}
          podman push ghcr.io/stefan79/${{ steps.package.outputs.name }}:latest

      - name: Notify Slack on Build Success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ New package version published successfully!\n• Version: `${{ steps.package.outputs.version }}`\n• Latest: https://ghcr.io/stefan79/${{ steps.package.outputs.name }}:latest\n• Versioned: https://ghcr.io/stefan79/${{ steps.package.outputs.name }}:${{ steps.package.outputs.version }}\n• Package page: https://github.com/${{ github.repository }}/pkgs/container/${{ steps.package.outputs.name }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}

      - name: Notify Slack on Build Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ Package build failed!\nSee: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GHACTION_WEBHOOK }}
